name: Deploy PYRA Barter Credit API

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    # Run daily at 6 AM UTC to update static files
    - cron: '0 6 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest requests-mock
    
    - name: Run tests
      run: |
        python -m pytest tests/ -v || echo "Tests not found, skipping..."
        python calculate_credit.py  # Test main calculation script
    
    - name: Test API endpoints
      run: |
        python app.py &
        sleep 10
        curl -f http://localhost:5000/health || exit 1
        pkill -f "python app.py"

  deploy-static:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Generate static JSON files
      env:
        COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
      run: |
        mkdir -p static-output
        python generate_static.py
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./static-output
        cname: pyra-credit.your-domain.com  # Replace with your domain

  deploy-heroku:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.14
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "your-pyra-credit-api"  # Replace with your Heroku app name
        heroku_email: "your-email@example.com"   # Replace with your email
        env_file: ".env.production"
      env:
        HD_COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
        HD_UPDATE_INTERVAL: "300"
        HD_PORT: "80"

  deploy-railway:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Railway
      run: |
        curl -fsSL https://railway.app/install.sh | sh
        railway login --token ${{ secrets.RAILWAY_TOKEN }}
        railway up
      env:
        COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}

  deploy-vercel:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        vercel-args: '--prod'
      env:
        COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}

  docker-build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ github.ref == 'refs/heads/main' }}
        tags: |
          your-dockerhub-username/pyra-barter-credit:latest
          your-dockerhub-username/pyra-barter-credit:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  update-documentation:
    runs-on: ubuntu-latest
    needs: [deploy-static, deploy-heroku]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v4
    
    - name: Update README with deployment URLs
      run: |
        sed -i 's|https://your-api-domain.com|https://your-pyra-credit-api.herokuapp.com|g' README.md
        sed -i 's|https://yourdomain.com|https://pyra-credit.your-domain.com|g' examples/*.html
        sed -i 's|YOUR_API_URL|https://your-pyra-credit-api.herokuapp.com|g' examples/*.html
    
    - name: Commit updated documentation
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --staged --quiet || git commit -m "Auto-update deployment URLs"
        git push || echo "No changes to push"
